INSERT INTO VAGA VALUES(2, false, 1);
INSERT INTO VAGA VALUES(3, false, 2);
INSERT INTO VAGA VALUES(32, false, 3);
INSERT INTO VAGA VALUES(17, false, 3);
INSERT INTO VAGA VALUES(42, false, 3);
INSERT INTO VAGA VALUES(18, true, 3);